[features]
seeds = false
skip-lint = false
[programs.localnet]
coode_staking = "A8FFovyJCj8J235sKfUiorYZB9o8qoLSG3EzGG554Ws"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/soso/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
